default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: crockswap_development

test:
  <<: *default
  database: crockswap_test

production:
  <<: *default
  database: crockswap_production
  username: crockswap
  password: <%= ENV['CROCKSWAP_DATABASE_PASSWORD'] %>

staging:
  <<: *default
  database: crockswap_staging
  username: crockswap
  password: <%= ENV['CROCKSWAP_DATABASE_PASSWORD'] %>
